### ISSUE TITLE
Bedrock block shapes update?

### ISSUE THREAD

**Issue by SuperLlama88888** [gentlegiantJGC/Minecraft-Model-Reader#35]
I'm wondering if the [Bedrock block shapes lookup](https://github.com/gentlegiantJGC/Minecraft-Model-Reader/blob/master/minecraft_model_reader/api/resource_pack/bedrock/blockshapes.json) will be updated to newer versions?
I'm also wondering, how did you get that file? Was it automatically generated or did you have to make it yourself?

Thank you for your time.

**Comment by gentlegiantJGC** [comment]
This was included in the resource pack of a really old version of the game.
It was removed a long time ago.
